vim.o.background = "dark"         -- theme bg
vim.o.hidden = true               -- Required to keep multiple buffers open multiple buffers
vim.o.wrap = false                -- Display long lines as just one line
vim.o.encoding= "utf-8"           -- The encoding displayed
vim.o.pumheight = 10              -- Makes popup menu smaller
vim.o.fileencoding = "utf-8"      -- The encoding written to file
vim.o.ruler = true                -- Show the cursor position all the time
vim.o.cmdheight = 2               -- More space for displaying messages
vim.o.mouse = 'a'                 -- Set mouse
vim.o.splitright = true           -- Vertical split alway to the right
--vim.o.t_Co = "256"              -- Suport 256 colors
vim.o.tabstop = 2                 -- Insert 2 spaces for a tab
vim.o.shiftwidth = 2              -- Change the number of space characters inserted for indentation
vim.o.smarttab = true             -- Makes tabbing smarter will realize you have 2 vs 4
vim.o.expandtab = true            -- Converts tabs to spaces
vim.o.smartindent = true          -- Makes indenting smart
vim.o.autoindent = true           -- Good auto indent
vim.o.laststatus = 0              -- Always display the status line
vim.o.number = true               -- Line numbers
vim.o.cursorline = true           -- Highlight current line
vim.o.showtabline = 2             -- Always show tabs
vim.o.updatetime=300              -- Faster completion
vim.o.timeoutlen=100              -- By default timeoutlen is 1000 ms
vim.o.clipboard = "unnamedplus"   -- Copy paste between vim and everything else
